import type { Product } from "./types";

export const mockProducts: Product[] = [
  {
    _id: "mock-torta-matilda",
    name: "Torta Matilda",
    slug: { current: "torta-matilda" },
    description:
      "18 cm $70.000 (2 rellenos) · 14 cm $30.000 (1 relleno) · 16 cm $45.000",
    price: 70000,
    category: "tortas",
  },
  {
    _id: "mock-tortas-buttercream",
    name: "Tortas buttercream",
    slug: { current: "tortas-buttercream" },
    description: "Desde $70.000",
    price: 70000,
    category: "tortas",
  },
  {
    _id: "mock-lemon-pie",
    name: "Lemon Pie",
    slug: { current: "lemon-pie" },
    description: "22 cm",
    price: 40000,
    category: "tartas",
  },
  {
    _id: "mock-cheesecake-frutos-rojos",
    name: "Cheesecake frutos rojos",
    slug: { current: "cheesecake-frutos-rojos" },
    description: "24 cm (12 a 15 porciones) · 16 cm $35.000 (8 porciones)",
    price: 60000,
    category: "tartas",
  },
  {
    _id: "mock-galletitas-decoradas",
    name: "Galletitas decoradas",
    slug: { current: "galletitas-decoradas" },
    description: "6 galletitas decoradas",
    price: 25000,
    category: "galletitas",
  },
  {
    _id: "mock-tortas-decoradas",
    name: "Tortas decoradas",
    slug: { current: "tortas-decoradas" },
    description: "20 porciones · Desde $90.000",
    price: 90000,
    category: "tortas",
  },
  {
    _id: "mock-mini-pasteleria",
    name: "Mini Pastelería",
    slug: { current: "mini-pasteleria" },
    description: "12 unidades · Desde $40.000",
    price: 50000,
    category: "mesas-dulces",
  },
  {
    _id: "mock-alfajores",
    name: "Alfajores",
    slug: { current: "alfajores" },
    description: "6 unidades: nuez, maicena, tipo Mardel, chips",
    price: 12000,
    category: "alfajores",
  },
  {
    _id: "mock-corazon-buttercream",
    name: "Corazón buttercream",
    slug: { current: "corazon-buttercream" },
    description: "Torta en forma de corazón con buttercream",
    price: 60000,
    category: "tortas",
  },
  {
    _id: "mock-budines",
    name: "Budines",
    slug: { current: "budines" },
    description: "650 g · Banana con nuez · Carrot cake",
    price: 15000,
    category: "budines",
  },
  {
    _id: "mock-torta-letra-numero",
    name: "Torta letra o número",
    slug: { current: "torta-letra-o-numero" },
    description: "Tortas personalizadas en forma de letra o número",
    price: 55000,
    category: "tortas",
  },
];

export const seedProducts = mockProducts.map((p) => ({
  _type: "product" as const,
  _id: p._id.replace("mock-", "product-"),
  name: p.name,
  slug: { _type: "slug" as const, current: p.slug.current },
  description: p.description,
  price: p.price,
  category: p.category,
  available: true,
}));
